instruction:
  course_type:
    undergraduate: 1
    elective: 1
    specialized: 1
    computer science: 1
    advanced: 1
    introductory: 1
    high school: 1
    professional development: 1
    certification: 1
    bootcamp: 1
    seminar: 1

  programming_paradigm:
    object-oriented: 1
    functional: 1
    procedural: 1
    declarative: 1
    logic-based: 1
    event-driven: 1
    modular: 1
    symbolic: 1
    aspect-oriented: 1
    multi-paradigm: 1

  additional_context:
    "": 1
    " Also, mention one real-world application where this concept is critical.": 1
    " Additionally, discuss a potential pitfall or misconception associated with this concept.": 1
    " Also, highlight its benefits over the alternative approach.": 1
    " Also, compare this concept with its predecessor.": 1
    " Additionally, share its significance in modern computing.": 1
    " Also, provide a historical context or origin of this concept.": 1
    " Also, mention one real-world application where this concept is critical.": 1
    " Additionally, discuss a potential pitfall or misconception associated with this concept.": 1
    " Also, highlight its benefits over the alternative approach.": 1
    " Also, compare this concept with its predecessor.": 1
    " Additionally, share its significance in modern computing.": 1
    " Also, provide a historical context or origin of this concept.": 1
    " Besides, can you recommend any books or resources for further reading?": 1
    " Also, how does this concept relate to recent trends in technology?": 1
    " Additionally, provide a visualization or diagram explaining this concept.": 1
    " Also, mention any notable personalities or experts associated with this concept.": 1
    " In addition, discuss the scalability aspects of this concept.": 1
    " Also, relate this concept to a famous algorithm or software.": 1

  depth:
    in detail: 1
    in simple terms: 1
    in depth: 1
    in a nutshell: 1
    from a historical perspective: 1
    from a practical perspective: 1
    highlighting its pros and cons: 1
    focusing on its applications: 1

  prompt_templates:
    "In a {course_type} course focused on the {programming_paradigm} paradigm in Python, the topic of {concept} is crucial. Please define a different but related concept {depth} and illustrate it with Python code.{additional_context}": 1
    "In a {course_type} course focused on the {programming_paradigm} paradigm in Python, the topic of {concept} is crucial. Please define this concept {depth} and illustrate it with Python code.{additional_context}": 1
    "There are {course_type} courses touching upon {programming_paradigm} paradigm which discuss {concept}. What is it, {depth}? Also, provide a relevant Python example.{additional_context}": 1
    "Often {course_type} courses touch upon {programming_paradigm} paradigm in Python often discuss {concept}. Can you think of a related concept and explain it {depth}? Also, provide a relevant Python example.{additional_context}": 1
    "In modern {course_type} courses, the emphasis on the {programming_paradigm} paradigm in Python has grown. Explore the topic of {concept} {depth} and provide practical Python examples.{additional_context}": 1
    "In modern {course_type} courses, the emphasis on the {programming_paradigm} paradigm in Python has grown. Explore a related but different {concept} {depth} and provide practical Python examples.{additional_context}": 1
    "With a focus on {programming_paradigm} paradigm, how would you introduce the topic of {concept} in a {course_type} course? Break it down {depth}.{additional_context}": 1
    "With a focus on {programming_paradigm} paradigm, how would you introduce a different but related concept to {concept} to our {course_type} course? Break it down {depth}.{additional_context}": 1

  concept:
    "numerical properties: associativity, commutativity, distributivity": 1
    fundamental theorem of arithmetic: 1
    prime factorization: 1
    GCD and LCM relationships: 1
    exponential properties: 1
    logarithm properties and bases: 1
    "complex numbers: basic operations": 1
    "complex numbers: polar form": 1
    "fraction operations: addition, subtraction, multiplication, division": 1
    decimal to fraction conversions: 1
    integer and fractional exponents: 1
    "equation properties: transitive, reflexive, symmetric": 1
